const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let records=[],page='overview',period='month',direction='支出',hidden=false,category=null;
const money=n=>hidden?'••••••':(n<0?'−':'')+'¥ '+(Math.abs(n)/100).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const sum=rs=>rs.reduce((a,r)=>a+r.amount_cents,0), total=(rs,d)=>sum(rs.filter(r=>r.direction===d));
function selection(){let prefix=$('#month').value.slice(0,period==='year'?4:7);return records.filter(r=>r.occurred_at.startsWith(prefix)&&(page==='invest'?r.nature==='投资':$('#nature').value==='all'||r.nature===$('#nature').value));}
function table(rs){return rs.length?`<table class="f-table"><thead><tr><th>交易 / 分类</th><th>日期</th><th>金额 / 元</th></tr></thead><tbody>${rs.map(r=>`<tr><td>${esc(r.category)}<div class="f-sub">${esc(r.note||r.category_group)} · ${esc(r.nature)}</div></td><td>${esc(r.occurred_at.slice(0,10))}</td><td>${r.direction==='收入'?'+':'−'}${money(r.amount_cents)}</td></tr>`).join('')}</tbody></table>`:'<p class="f-sub">此范围暂无交易。</p>';}
function groups(rs){const m=new Map();rs.filter(r=>r.direction===direction).forEach(r=>{let x=m.get(r.category_id)||{id:r.category_id,name:r.category,value:0};x.value+=r.amount_cents;m.set(r.category_id,x)});return [...m.values()].sort((a,b)=>b.value-a.value);}
function ranks(rs){let g=groups(rs),t=total(rs,direction);return g.length?(page==='overview'?g.slice(0,5):g).map(r=>`<div class="f-rank"><button data-category="${r.id}"><div class="f-rankline"><span>${esc(r.name)}</span><b>${money(r.value)} · ${hidden?'—':(r.value/t*100).toFixed(1)+'%'}</b></div><div class="f-track"><div class="f-fill" style="width:${hidden?0:r.value/t*100}%"></div></div></button></div>`).join(''):'<p class="f-sub">此范围暂无记录。</p>';}
function trend(rs){if(hidden)return '<p class="f-sub">金额及图表已隐藏。</p>';const year=$('#month').value.slice(0,4), base=records.filter(r=>r.occurred_at.startsWith(year)&&(page==='invest'?r.nature==='投资':$('#nature').value==='all'||r.nature===$('#nature').value));const vals=Array.from({length:12},(_,i)=>{const r=base.filter(r=>Number(r.occurred_at.slice(5,7))===i+1);return [total(r,'收入'),total(r,'支出')]});const max=Math.max(...vals.flat(),1);return `<svg class="f-chart" viewBox="0 0 600 250" role="img" aria-label="${year}年月度收入支出，单位元"><text x="0" y="15">${money(max)}</text><line x1="0" y1="210" x2="600" y2="210" stroke="#ddd"/>${vals.map((v,i)=>v.map((n,j)=>`<rect x="${i*50+8+j*15}" y="${210-n/max*175}" width="12" height="${n/max*175}" rx="3" fill="${j?'#afc9ed':'#007aff'}"><title>${i+1}月${j?'支出':'收入'} ${money(n)}</title></rect>`).join('')+`<text x="${i*50+20}" y="235" text-anchor="middle">${i+1}</text>`).join('')}</svg>`;}
function render(){const rs=selection(),inc=total(rs,'收入'),out=total(rs,'支出');const names={overview:'财务总览',analysis:'收支分析',invest:'投资记录',transactions:'全部交易'};$('#crumb').textContent=names[page];$('#title').textContent={overview:'让财务，清晰一点。',analysis:'每一笔，都有迹可循。',invest:'看清已记录的投资收支。',transactions:'每一笔，都在这里。'}[page];$('#subtitle').textContent=`${$('#month').value.slice(0,period==='year'?4:7)} · ${page==='invest'?'投资':$('#nature').selectedOptions[0].text} · ${rs.length} 笔 · 账本截至 ${records[0]?.occurred_at.slice(0,10)||'暂无数据'}`;document.querySelectorAll('[data-page]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.page===page));document.querySelectorAll('[data-period]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.period===period));const stats=`<div class="f-stats">${[['收支差额',inc-out],['收入',inc],['支出',out]].map(([name,v])=>`<div class="f-stat"><div class="f-label">${name}</div><div class="f-num">${money(v)}</div><div class="f-caption">${name==='收支差额'?'收入 − 支出，非账户余额':'所选范围累计'}</div></div>`).join('')}</div>`;const structure=`<section class="f-panel"><div class="f-panelhead"><h2>收支构成</h2><div class="f-segment"><button data-direction="支出" aria-pressed="${direction==='支出'}">支出</button><button data-direction="收入" aria-pressed="${direction==='收入'}">收入</button></div></div>${ranks(rs)}</section>`;const details=category!==null?`<section class="f-panel f-bottom"><div class="f-panelhead"><h2>分类明细 · ${esc(rs.find(r=>r.category_id===category)?.category||'')}</h2><button data-close>收起</button></div>${table(rs.filter(r=>r.category_id===category&&r.direction===direction))}</section>`:'';$('#content').innerHTML=stats+(page==='transactions'?`<section class="f-panel">${table(rs)}</section>`:page==='overview'?`<div class="f-grid"><section class="f-panel"><div class="f-panelhead"><h2>年度收支趋势</h2><div class="f-legend"><span>收入</span><span>支出</span></div></div>${trend(rs)}</section>${structure}</div>${details}<section class="f-panel f-bottom"><div class="f-panelhead"><h2>最近收支</h2><button data-page="transactions">查看全部</button></div>${table(rs.slice(0,8))}</section>`:page==='analysis'?`<div class="f-grid">${structure}<section class="f-panel"><h2>本期观察</h2><div class="f-note">${groups(rs)[0]?`最大${direction}分类为 ${esc(groups(rs)[0].name)}，金额 ${money(groups(rs)[0].value)}。`:'暂无可分析记录。'}</div><div class="f-note">按所选性质统计；往来、调整可分别查看。时间沿用账本原始日期，未进行时区换算。</div></section></div>${details}`:`<section class="f-panel"><h2>投资账本收支趋势</h2><p class="f-sub">深蓝为收入，浅蓝为支出。仅反映账本记录；暂无持仓、成本和行情数据，无法计算持仓市值、浮动收益或收益率。</p>${trend(rs)}</section><section class="f-panel f-bottom"><h2>投资交易记录</h2>${table(rs)}</section>`);}
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.page){page=b.dataset.page;category=null;}else if(b.dataset.period){period=b.dataset.period;category=null;}else if(b.dataset.direction){direction=b.dataset.direction;category=null;}else if(b.dataset.category){category=Number(b.dataset.category);}else if(b.hasAttribute('data-close'))category=null;else if(b.id==='privacy'){hidden=!hidden;b.textContent=hidden?'显示金额':'隐藏金额';b.setAttribute('aria-pressed',hidden);}else return;render();});
$('#month').onchange=$('#nature').onchange=()=>{category=null;render()};
fetch('/api/ledger').then(r=>{if(!r.ok)throw Error();return r.json()}).then(rs=>{records=rs;$('#month').value=records[0]?.occurred_at.slice(0,7)||new Date().toISOString().slice(0,7);render()}).catch(()=>{$('#content').textContent='账本读取失败，请刷新重试。'});
